// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3nws1WUFdBQRQfaxUelaC-yuwsfL1nIE',
    appId: '1:500250036137:web:600814e6f3b44a2ab6a6b8',
    messagingSenderId: '500250036137',
    projectId: 'burble-life-e6801',
    authDomain: 'burble-life-e6801.firebaseapp.com',
    storageBucket: 'burble-life-e6801.firebasestorage.app',
    measurementId: 'G-N0L9BHKSGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX1BPYzzx9keyCePfdysMXS79KgnTbUuE',
    appId: '1:1013801564077:android:409a1ac99377d82bbf1324',
    messagingSenderId: '1013801564077',
    projectId: 'pickupmycar-c01db',
    storageBucket: 'pickupmycar-c01db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg4osiXRPddFSIQxgY2Nz8O4DbLSuIo-k',
    appId: '1:1013801564077:ios:5afdfa67f5148c2abf1324',
    messagingSenderId: '1013801564077',
    projectId: 'pickupmycar-c01db',
    storageBucket: 'pickupmycar-c01db.firebasestorage.app',
    iosBundleId: 'com.pickupmycar.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYuRDdhMQC4bLLvoOt4zqZ2boQKfNTCQE',
    appId: '1:500250036137:ios:4c1cffc6c55095eab6a6b8',
    messagingSenderId: '500250036137',
    projectId: 'burble-life-e6801',
    storageBucket: 'burble-life-e6801.firebasestorage.app',
    androidClientId:
        '500250036137-3ohqa7gc4hv0eu67je664jt55vvnnknh.apps.googleusercontent.com',
    iosClientId:
        '500250036137-0u3as5ffski3nb8qe4mnvq7ph9jn6g7r.apps.googleusercontent.com',
    iosBundleId: 'com.burblelife.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3nws1WUFdBQRQfaxUelaC-yuwsfL1nIE',
    appId: '1:500250036137:web:f37eaedb45a93cadb6a6b8',
    messagingSenderId: '500250036137',
    projectId: 'burble-life-e6801',
    authDomain: 'burble-life-e6801.firebaseapp.com',
    storageBucket: 'burble-life-e6801.firebasestorage.app',
    measurementId: 'G-00ZD8JP6SS',
  );
}
